### ISSUE TITLE
Systematic RPC request on pageload is wasteful

### ISSUE THREAD

**Issue by odony** [Tardo/OdooInfo#2]
Context: users of this extension have found themselves blocked on odoo.com when the RPC rate-limiting was made more strict.

It turns out that if you open several tabs on a single Odoo website (let's say you open a series of forum questions with the same tag to read them), you're going to fire several `/jsonrpc` for each tab.
Even if you're not using the extension.
All of them requesting the exact same info.

This could be avoided easily I think. 

The ideal behavior would be to depend only on `session_info` when it is available, otherwise wait until the user asks for the info to load it. Currently all Odoo websites are aware of which users are using the extension, all the time, passively.
And even if on-demand loading is not desired, you could cache the information for some time (let's say 1 hour) in the local storage, instead of reloading it constantly.

PS: The same problem exists in the OdooTerminal extension apparently

**Comment by Tardo** [comment]
Sorry I haven't read this until now! I will have to review it and opt for one of the strategies you have mentioned.

**Comment by Tardo** [comment]
Thx for report!
